/*
 * shiftreg_conf.h
 *
 * Created on: Jun 2, 2025
 * Author: alex
 */

#ifndef INC_SHIFTREG_CONF_H_
#define INC_SHIFTREG_CONF_H_

// PA2 -> RCLK
#define SHIFTREG_RCK_GPIO_EXPANDER 				GPIOA
#define SHIFTREG_RCK_GPIO_PIN 					GPIO_PIN_2
#define SHIFTREG_RCK_SPEED_SETTING 				GPIO_SPEED_FREQ_VERY_HIGH
#define SHIFTREG_RCK_EXTERNAL_PULLUP_OHMS 		1000	// ohms
#define SHIFTREG_RCK_CAPACITANCE_PICOFARADS 	50		// pF

// PA3 -> SRCK
#define SHIFTREG_SRCK_GPIO_EXPANDER 			GPIOA
#define SHIFTREG_SRCK_GPIO_PIN 					GPIO_PIN_3
#define SHIFTREG_SRCK_SPEED_SETTING 			GPIO_SPEED_FREQ_VERY_HIGH
#define SHIFTREG_SRCK_EXTERNAL_PULLUP_OHMS 		1000	// ohms
#define SHIFTREG_SRCK_CAPACITANCE_PICOFARADS 	50		// pF

// PB9 -> SIN
#define SHIFTREG_SIN_GPIO_EXPANDER 				GPIOB
#define SHIFTREG_SIN_GPIO_PIN 					GPIO_PIN_9
#define SHIFTREG_SIN_SPEED_SETTING 				GPIO_SPEED_FREQ_VERY_HIGH
#define SHIFTREG_SIN_EXTERNAL_PULLUP_OHMS 		1000	// ohms
#define SHIFTREG_SIN_CAPACITANCE_PICOFARADS 	50		// pF

// PB8 -> nG
#define SHIFTREG_NG_GPIO_EXPANDER 				GPIOB
#define SHIFTREG_NG_GPIO_PIN 					GPIO_PIN_8
#define SHIFTREG_NG_SPEED_SETTING 				GPIO_SPEED_FREQ_VERY_HIGH
#define SHIFTREG_NG_EXTERNAL_PULLUP_OHMS 		1000	// ohms
#define SHIFTREG_NG_CAPACITANCE_PICOFARADS 		50 		// pF

#endif /* INC_SHIFTREG_CONF_H_ */
